---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: guestnook-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/samuelbartels20/guestbook-gitops

